services:
  ros2:
    build:
      context: ..
      dockerfile: docker/dockerfile
      args:
        USERNAME: agrodroid
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}

    image: tx2-ros2-humble:robot

    container_name: ros2_humble_tx2

    user: agrodroid



    network_mode: host
    ipc: host

    privileged: true

    volumes:
      - /dev:/dev
      - ../ros2_ws:/ros2_ws

    environment:
      ROS_DOMAIN_ID: "10"
      RMW_IMPLEMENTATION: rmw_fastrtps_cpp

    restart: unless-stopped

    command: >
      bash -lc "source /opt/ros/humble/setup.bash
      && cd /ros2_ws
      && colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release
      && source install/setup.bash
      && ros2 launch robot_bringup robot_bringup.launch.py"
