services:
  ros2:
    build:
      context: .
      dockerfile: dockerfile
      args:
        USERNAME: agrodroid
        USER_UID: 1000
        USER_GID: 1000

    image: tx2-ros2-humble:robot

    container_name: ros2_humble_tx2



    network_mode: host
    ipc: host

    privileged: true

    volumes:
      - /dev:/dev
      - /home/agrodroid/releases/active_release/ws:/ros2_ws

    environment:
      ROS_DOMAIN_ID: "10"
      RMW_IMPLEMENTATION: rmw_fastrtps_cpp

    restart: unless-stopped

    command: sleep infinity
