FROM ros:humble-ros-base

ENV DEBIAN_FRONTEND=noninteractive
ENV ROS_DISTRO=humble
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV PIP_ROOT_USER_ACTION=ignore

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    git \
    curl \
    wget \
    nano \
    vim \
    tmux \
    htop \
    screen \
    minicom \
    net-tools \
    iproute2 \
    iputils-ping \
    libspdlog-dev \
    libudev-dev \
    python3-pip \
    python3-serial \
    python3-colcon-common-extensions \
    python3-vcstool \
    python3-argcomplete \
    python3-rosdep \
    ros-dev-tools \
    ros-humble-demo-nodes-cpp \
    ros-humble-demo-nodes-py \
    ros-humble-bond \
    ros-humble-bondcpp \
    ros-humble-diagnostic-msgs \
    ros-humble-diagnostic-updater \
    ros-humble-teleop-twist-keyboard \
    ros-humble-nav2-lifecycle-manager \
    ros-humble-nav2-msgs \
    ros-humble-nav2-util \
    ros-humble-rclcpp \
    ros-humble-rclcpp-components \
    ros-humble-rclcpp-lifecycle \
    ros-humble-xacro \
    ros-humble-tf2-tools \
    ros-humble-joint-state-publisher \
    ros-humble-robot-state-publisher \
    && rm -rf /var/lib/apt/lists/*

COPY ros2_ws/requirements.txt /tmp/ros2_requirements.txt
RUN pip3 install --no-cache-dir -r /tmp/ros2_requirements.txt

RUN if [ ! -f /etc/ros/rosdep/sources.list.d/20-default.list ]; then rosdep init; fi

ARG USERNAME=agrodroid
ARG USER_UID=1000
ARG USER_GID=1000

RUN groupadd --gid ${USER_GID} ${USERNAME} \
    && useradd --uid ${USER_UID} --gid ${USER_GID} -m ${USERNAME} \
    && usermod -aG dialout,video,audio,plugdev ${USERNAME}

RUN echo "source /opt/ros/humble/setup.bash" >> /home/${USERNAME}/.bashrc
RUN echo "[ -f /ros2_ws/install/setup.bash ] && source /ros2_ws/install/setup.bash" >> /home/${USERNAME}/.bashrc

USER ${USERNAME}

WORKDIR /ros2_ws

CMD ["bash"]
